name: Export i18n Strings

on: [push]

jobs:
  export_strings_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Create PR action
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Run and commit changes
        run: |
         git config user.name "GitHub Actions"
         git config user.email noreply@github.com
         echo  $GITHUB_WORKSPACE
         ls
         touch demo-output.txt
         ls
      - name: Create pull request
        uses: gdcorp-action-public-forks/peter-evans-create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
          head: ${{ github.ref }}
          base: test-branch-1
          branch-suffix: random
          branch: automated-demo-branch
          title: "BOT: Export Localized Strings"
          body: |

            This is an automatic workflow to export our localized strings.

            # What's next?
            - [ ] Check the diff of this pull request, to verify that the export strings was run successfully and that there are new strings to export.
            - [ ] Assign yourself to the PR
            - [ ] Rename this PR and remove the `BOT:` prefix so folks know it can be merged.
            - [ ] Consider automating any one of these steps ☝️ to help the next developer that needs to do this.
          labels: automated
