name: Run Post Code Coverage Status

on:
  pull_request:
    types: [opened, unlabeled, labeled, reopened, synchronize]



jobs:
  post_code_coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN_DEMO }}
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: '100'
        lfs: 'true'
    - name: Fetch Current Code Coverage
      id: vars
    - run: echo ::set-output name=coverageReport::$(cat TestCoverageAnalyser/totalCoverage.txt)
    - name: Comment on PR
       uses: actions/github-script@v3
        with:
         script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Code Coverage'  ${{ steps.vars.outputs.version }},
            })
