name: Post Code Coverage Status

on:
  pull_request:
    types: [opened, unlabeled, labeled, reopened, synchronize]

jobs:
  post_code_coverage:
    runs-on: ubuntu-latest
    env:
       CODE_COV: 10
    steps:
      - name: Fetch current code coverage report
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: '100'
          lfs: 'true'
        id: report
      - run: echo "CODE_COV=400" >> $GITHUB_ENV
      - name: Create Coverage Comment
        uses: actions/github-script@v3
        with:
         script: |
          github.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: 'Code Coverage: ${{ env.CODE_COV }}',
          })
      - run: echo 'output is ${{ env.CODE_COV }}'
