name: Run Danger

on:
  pull_request:
    types: [opened, unlabeled, labeled, reopened, synchronize]

jobs:
  run_danger:
    runs-on: ubuntu-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.CREATE_PR_TOKEN }}
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: '100'
          lfs: 'true'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
           ${{ runner.os }}-gem-
      - run: gem install bundler
      - run: |
          bundle config path vendor/bundle
          bundle install
          bundle exec danger --fail-on-errors=true
