name: Post Code Coverage Status

on:
  pull_request:
    types: [opened, unlabeled, labeled, reopened, synchronize]

jobs:
  post_code_coverage:
    runs-on: ubuntu-latest
    env:
       CODE_COV: 0
       CODE_COV_MAIN: 0
    steps:
      - name: Fetch main branch code coverage report
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: '1'
          lfs: 'false'
          ref: main
      - run: echo "CODE_COV_MAIN= $(cat TestCoverageAnalyser/totalCoverage.txt)" >> $GITHUB_ENV
      - name: Fetch current code coverage report
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: '1'
          lfs: 'false'
      - run: echo "CODE_COV= $(cat TestCoverageAnalyser/totalCoverage.txt)" >> $GITHUB_ENV
      - name: Create Coverage Comment
        uses: actions/github-script@v3
        with:
         script: |
          github.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: '# Code Coverage Report\n | ${{ GITHUB_REF }} | Develop | \n --------------|--------- \n ${{ env.CODE_COV }} | ${{ env.CODE_COV_MAIN }}',
          })
